#!/bin/bash

set -euo pipefail

VERT='\033[0;32m'
JAUNE='\033[1;33m'
NC='\033[0m'

echo -e "${VERT}                                   ▄▄                    ${NC}"
echo -e "${VERT}                  █▄                ██       █▄  █▄      ${NC}"
echo -e "${VERT}       ▄          ██                ██      ▄██▄▄██▄     ${NC}"
echo -e "${VERT} ▄▀▀█▄ ████▄▄███▀ ████▄ ▄██▀█ ████▄ ██ ▄▀▀█▄ ██  ██ ▄██▀█${NC}"
echo -e "${VERT} ▄█▀██ ██   ██    ██ ██ ▀███▄ ██ ██ ██ ▄█▀██ ██  ██ ▀███▄${NC}"
echo -e "${VERT}▄▀█▄██▄█▀  ▄▀███▄▄██ ███▄▄██▀▄████▀▄██▄▀█▄██▄██ ▄███▄▄██▀${NC}"
echo -e "${VERT}                              ██                         ${NC}"
echo -e "${VERT}                              ▀                          ${NC}"

echo -e "${JAUNE}Bienvenue dans le script de configuration Archsplatts !${NC}\n"

echo -e "${JAUNE}(Veuillez activer le dépôt multilib avant de commencer)${NC}\n"

if [ -t 0 ]; then
    read -p "Appuyez sur Entrée pour continuer... "
fi   

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[1/11] Mise à jour des miroirs${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

sudo pacman -S --needed --noconfirm reflector
sudo reflector --country France,Germany --latest 5 --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist --verbose

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[2/11] Installation des pilotes GPU${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

 AMD_PKGS=(
	"lib32-mesa"
	"lib32-vulkan-icd-loader"
	"lib32-vulkan-radeon"
	"mesa" 
	"vulkan-icd-loader"
	"vulkan-radeon"
)
 
sudo pacman -S --needed --noconfirm "${AMD_PKGS[@]}"

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[3/11] Installation de Sway${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

 DE_PKGS=(
	"autotiling" 
	"flameshot" 
	"foot"
	"gammastep" 
	"grim"
	"mako"
	"pavucontrol"
	"polkit" 
	"polkit-gnome"  
	"qt6-wayland"
	"rofi" 
	"sddm"
	"slurp"
	"sway"
	"swaybg"
	"swayidle"
	"swaylock"
	"thunar"
	"thunar-archive-plugin"
	"thunar-media-tags-plugin"
	"thunar-volman"
	"waybar"
	"wl-clipboard"
	"wl-clip-persist"
	"wmenu"
	"xdg-desktop-portal-gtk" 
	"xdg-desktop-portal-wlr" 
	"xorg-xwayland"
)

sudo pacman -S --needed --noconfirm "${DE_PKGS[@]}"

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[4/11] Installation des paquets multimedia${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

MULTIMEDIA_PKGS=(
	"audacity"
	"discord" 
	"ffmpegthumbnailer"
	"firefox" 
	"flac"
	"gamemode" 
	"gst-libav"
	"gst-plugins-bad"
	"gst-plugins-base" 
	"gst-plugins-good" 
	"gst-plugins-ugly"
	"lib32-flac"
	"lib32-gamemode"
	"lib32-mangohud" 
	"mangohud"
	"mpv"
	"qbittorrent"
	"rhythmbox"
	"sof-firmware"
	"steam" 
	"thunderbird" 
	"webkit2gtk-4.1"
)

sudo pacman -S --needed --noconfirm "${MULTIMEDIA_PKGS[@]}"

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[5/11] Installation des utilitaires${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

UTILS_PKGS=(
	"arch-wiki-docs"
	"base-devel"
	"bat" 
	"btop" 
	"calcurse"
	"cliphist"
	"dust" 
	"eza"
	"fastfetch" 
	"galculator"
	"geany" 
	"git"
	"gvfs"
	"gvfs-mtp" 
	"hyprpicker"
	"impression" 
	"lact" 
	"linux"
	"man-db"
	"man-pages"
	"man-pages-fr"
	"micro" 
	"nwg-displays"
	"nwg-look"
	"pacman-contrib" 
	"realtime-privileges" 
	"ristretto"
 	"starship"
 	"termdown"
	"timeshift" 
	"trash-cli" 
	"tumbler"
	"ufw" 
	"unzip"
	"wev"
	"wget" 
	"xarchiver"
	"yazi" 
	"zathura"
	"zathura-pdf-mupdf"
	"zip"
	"zsh"
	"zsh-autosuggestions" 
	"zsh-syntax-highlighting"
)

sudo pacman -S --needed --noconfirm "${UTILS_PKGS[@]}"

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[6/11] Installation des thèmes & polices${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

THEMES_PKGS=(
	"breeze-cursors" 
	"noto-fonts"
	"noto-fonts-emoji"
	"noto-fonts-extra"
	"papirus-icon-theme" 
	"ttf-nerd-fonts-symbols"
	"ttf-nerd-fonts-symbols-common"
	"ttf-ubuntu-font-family" 
	"ttf-ubuntu-mono-nerd"
)

sudo pacman -S --needed --noconfirm "${THEMES_PKGS[@]}"

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[7/11] Installation de yay (AUR Helper)${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
yay -S brave-origin-bin mangowm

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[8/11] Activation des services système${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

sudo ufw enable
sudo systemctl enable --now ufw.service
sudo systemctl enable --now lactd.service
sudo systemctl enable sddm

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[9/11] Configuration du shell${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

chsh -s /bin/zsh

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[10/11] Copie des dotfiles${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

mkdir -p $HOME/.config
mkdir -p $HOME/.scripts
mkdir -p $HOME/Images/Wallpapers
mkdir -p $HOME/.local/share/themes
cd $HOME/arch-config
cp -r config/* $HOME/.config
cp -r appearance/* $HOME/.scripts
cp zshrc $HOME/.zshrc
cp koi.jpg $HOME/Images/Wallpapers/koi.jpg
chmod u+x $HOME/.config/mango/autostart.sh
chmod u+x $HOME/.config/mango/scripts/*
chmod u+x $HOME/.config/mango/waybar/scripts/*
chmod u+x $HOME/.config/rofi/scripts/*

echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${JAUNE}[11/11] Catppuccin papirus folders${NC}"
echo -e "${JAUNE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

git clone https://github.com/catppuccin/papirus-folders.git
cd papirus-folders
sudo cp -r src/* /usr/share/icons/Papirus
chmod u+x $HOME/.scripts/papirus-folders
$HOME/.scripts/papirus-folders -C cat-mocha-blue

echo -e "${VERT}╔════════════════════════════════════════╗${NC}"
echo -e "${VERT}║  Installation terminée avec succès !   ║${NC}"
echo -e "${VERT}╚════════════════════════════════════════╝${NC}\n"

echo -e "${JAUNE}⚠ Veuillez redémarrer votre système pour appliquer tous les changements.${NC}\n"
