# --- Environnement & DBus --- #
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY 
exec systemctl --user import-environment XDG_CURRENT_DESKTOP

# --- Services système --- #
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec wl-paste --watch cliphist store

# --- Utilitaires --- #
exec gammastep   
exec mako

# --- Tiling --- #
exec autotiling &
