#!/usr/bin/env bash

op=$( echo -e " Poweroff\n Reboot\n Logout" | rofi -i -dmenu | awk '{print tolower($2)}' )

case $op in 
        poweroff)
                ;&
        reboot)
                systemctl $op
                ;;
        logout)
                swaymsg exit
                ;;
esac
