#!/bin/bash

official_updates=$(checkupdates 2>/dev/null | wc -l)
aur_updates=0

if command -v yay &> /dev/null; then
    aur_updates=$(yay -Qua 2>/dev/null | wc -l)
fi   

total_updates=$((official_updates + aur_updates))

if [ "$total_updates" -gt 0 ]; then

  notify-send -u normal \
        --icon=update-notifier \
        "Mises à jour disponibles" \
        "$total_updates paquets à mettre à jour (Officiel + AUR)"
        
    echo "{\"text\": \"$total_updates\", \"alt\": \"has-updates\", \"class\": \"has-updates\", \"tooltip\": \"Mises à jour : $total_updates\"}"
else
    echo "{\"text\": \"\", \"alt\": \"updated\", \"class\": \"updated\", \"tooltip\": \"Système à jour\"}"
fi   
