#!/bin/bash

# Afficher le menu et capturer la sélection
selection=$(echo -e "󰔛  5 minutes\n󰔛 10 minutes\n󰔛 15 minutes\n󰔛 20 minutes\n󰔛 25 minutes\n󰔛 30 minutes"| rofi -dmenu -config ~/.config/rofi/alarm-window.rasi)

# Vérifier si une sélection a été faite
if [[ -n "$selection" ]]; then
    case "$selection" in
        "󰔛  5 minutes")
			foot termdown -t Terminé -f standard 5m
			;;
        "󰔛 10 minutes")
			foot termdown -t Terminé -f standard 10m
            ;;
        "󰔛 15 minutes")
        	foot termdown -t Terminé -f standard 15m
            ;;  
        "󰔛 20 minutes")
			foot termdown -t Terminé -f standard 20m
            ;;      
              
        "󰔛 25 minutes")
			foot termdown -t Terminé -f standard 25m
            ;;
         
        "󰔛 30 minutes")
			foot termdown -t Terminé -f standard 30m
            ;;
    esac
fi   
