#!/bin/bash

options="Bleachbit\0icon\x1fbleachbit
Btop\0icon\x1fbtop
Impression\0icon\x1fio.gitlab.adhami3310.Impression
Timeshift\0icon\x1ftimeshift
VirtualBox\0icon\x1fvirtualbox"

selection=$(echo -e "$options" | rofi -dmenu -show-icons -icon-theme "Papirus" -config ~/.config/rofi/system-menu.rasi)

if [[ -n "$selection" ]]; then
    case "$selection" in
        "Bleachbit")
            bleachbit
            ;;
        "Btop")
            foot btop
            ;;
       	"Impression")                    
            impression
             ;;
        "Timeshift")
            timeshift-launcher
            ;;
        "VirtualBox")
            virtualbox
            ;;
    esac
fi   
