monitor.alsa.rules = [
  {
    matches = [
      {
       device.product.name = "Starship/Matisse HD Audio Controller"
      }
    ]
    actions = {
      update-props = {
        node.description = "Facade"
      }
    }
  }
]
