monitor.alsa.rules = [
  {
    matches = [
      {
       node.description = "Starship/Matisse HD Audio Controller Stéréo analogique"
      }
    ]
    actions = {
      update-props = {
        node.description = "Micro Facade"
      }
    }
  }
]
